name: Documentation
on: [push, pull_request]
jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      - name: Install deps and build (with cache)
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2
      
      - name: Install
        run: pnpm install
      
      - name: Build 💻
        run: pnpm run build
      
      - name: Generate Docs 📖
        run: pnpm run docs:html
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs